### ISSUE TITLE
The link for "Chinese sentences written by native Chinese speakers" in README.md is wrong

### ISSUE THREAD

**Issue by XuanxuanGao** [li-xirong/flickr8kcn#4]
Hi, thanks for opening access to the Chinese version of Flickr8k. I found that the link for "Chinese sentences written by native Chinese speakers" in README.md is wrong, which makes me confused for a while. I guess you may want to correct it.

**Comment by li-xirong** [comment]
Indeed.  Fixed. Thanks much!
